version: 2.1

executors:
  notebook-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo

jobs:
    Build_JDAT_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: bash ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: python ./.circleci/builder/factory.py -c jdat_notebooks
            - run:
                name: Collect Arifacts
                command: echo 'one'

                # Build_HST_NB_VIZ_Notebooks:
                #     executor: notebook-executor
                #     environment:
                #         PYTHONPATH: ./.circleci
                #     steps:
                #         - checkout
                #         - run:
                #             name: Setup Environment
                #             command: bash ./.circleci/setup_env.sh
                #         - run:
                #             name: Build Notebooks
                #             command: python ./.circleci/builder/factory.py -c hst_nb_viz
                # Build_Jupyter_Platform_Notebooks:
                #     executor: notebook-executor
                #     environment:
                #         PYTHONPATH: ./.circleci
                #     steps:
                #         - checkout
                #         - run:
                #             name: Setup Environment
                #             command: bash ./.circleci/setup_env.sh
                #         - run:
                #             name: Build Notebooks
                #             command: python ./.circleci/builder/factory.py -c jupyter_platform
                # Build_JWST_NB_VIZ_Notebooks:
                #     executor: notebook-executor
                #     environment:
                #         PYTHONPATH: ./.circleci
                #     steps:
                #         - checkout
                #         - run:
                #             name: Setup Environment
                #             command: bash ./.circleci/setup_env.sh
                #         - run:
                #             name: Build Notebooks
                #             command: python ./.circleci/builder/factory.py -c jwst_nb_viz
                # Build_Concept_APIS:
                #     executor: notebook-executor
                #     environment:
                #         PYTHONPATH: ./.circleci
                #     steps:
                #         - checkout
                #         - run:
                #             name: Setup Environment
                #             command: bash ./.circleci/setup_env.sh
                #         - run:
                #             name: Build Notebooks
                #             command: python ./.circleci/builder/factory.py -c concept_APIs
    Deploy_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - run:
              name: Collect HTML Pages
              command: echo 'one'
            - run:
              name: Store Artifacts
              command: echo 'two'
            - run:
              name: Deploy Artifacts
              command: echo 'three'

workflows:
  version: 2.1

  build-deploy:
    jobs:
        - Build_JDAT_Notebooks
        - Build_HST_NB_VIZ_Notebooks
        - Build_Jupyter_Platform_Notebooks
        - Build_JWST_NB_VIZ_Notebooks
        - Build_Concept_APIS
        - Deploy_Notebooks:
          requires:
            - Build_JDAT_Notebooks
            - Build_HST_NB_VIZ_Notebooks
            - Build_Jupyter_Platform_Notebooks
            - Build_JWST_NB_VIZ_Notebooks
            - Build_Concept_APIS


