version: 2.1

executors:
  notebook-executor:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo

jobs:
    Build_JDAT_Notebooks:
        executor: notebook-executor
        environment:
            PYTHONPATH: ./.circleci
        steps:
            - checkout
            - run:
                name: Setup Environment
                command: bash ./.circleci/setup_env.sh
            - run:
                name: Build Notebooks
                command: python ./.circleci/builder/factory.py -o build-notebooks -c jdat_notebooks

            - run:
                name: Build Website
                command: python ./.circleci/builder/factory.py -o build-website -c jdat_notebooks

            - store_artifacts:
                path: ./pages

            - run:
                name: "Built Notebooks are available at:"
                command: NB_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/pages/index.html"; echo $NB_URL

workflows:
  version: 2.1
  build-deploy:
      jobs:
          - Build_JDAT_Notebooks
